name: build-test-delploy-lambda
on: push

jobs:
  build-tests:
    name: build and tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      
      # Setup Go
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.18.0'
          
      # Cache go
      - name: Cache Go build and mod
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: ${{ runner.os }}-go-
          
      # Run build
      - name: Build
        run: go build 
        
      # Run vet
      - name: Go vet
        run: go vet ./...
      
      # Run testing on the code
      - name: Test
        run: go test ./... -v

      - name: Cache build
        uses: actions/cache@v3
        with:
          path: TrendInsight
          key: ${{ runner.os }}-TrendInsight-${{ hashFiles('TrendInsight') }}

  delploy-lambda:
    name: deploy lambda function
    runs-on: ubuntu-latest
    needs: build-tests
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Restore build
        uses: actions/cache@v3
        with:
          path: TrendInsight
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: ${{ runner.os }}-TrendInsight-
      - name: Zip build
        run: zip TrendInsight.zip TrendInsight
      - name: AWS Lambda Deploy
        uses: appleboy/lambda-action@v0.1.5
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: ${{ secrets.AWS_REGION }}
          function_name: trend-insight-publisher
          zip_file: TrendInsight.zip

