name: CI

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      
      # Setup Go
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.18.0'
          
      # Run build
      - name: Run build
        run: go build 
        
      # Run vet
      - name: Run vet
        run: |
          go vet ./...
      
      # Run testing on the code
      - name: Run testing
        run: go test ./... -v